// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using DataBase_First.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DataBase_First.Models
{
    public partial interface IITIDbContextProcedures
    {
        Task<List<getNumberOfStudentPerDepartmentResult>?> getNumberOfStudentPerDepartmentAsync(OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<SP_GetDataOfStudentByIdResult>?> SP_GetDataOfStudentByIdAsync(int? id, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<SP_GetStudentDataByStudentAddressResult>?> SP_GetStudentDataByStudentAddressAsync(string? address, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<SP_UpdateNewEmployeeResult>?> SP_UpdateNewEmployeeAsync(int? oldEmp, int? newEmp, int? pNum, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<SpDeleteTopicbyIdResult>?> SpDeleteTopicbyIdAsync(int? topId, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
    }
}
