// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DataBase_First.Models;

public partial class ManagerTopic
{
    public string? ManagerName { get; set; }

    public string? TopicName { get; set; }
}