// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace DataBase_First.Models
{
    public partial class SP_GetStudentDataByStudentAddressResult
    {
        public int St_Id { get; set; }
        [StringLength(50)]
        public string? St_Fname { get; set; }
        [StringLength(100)]
        public string? St_Address { get; set; }
    }
}
