// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace DataBase_First.Models
{
    public partial class SP_GetDataOfStudentByIdResult
    {
        public int St_Id { get; set; }
        [StringLength(50)]
        public string? St_Fname { get; set; }
        public string? St_Lname { get; set; }
        [StringLength(100)]
        public string? St_Address { get; set; }
        public int? St_Age { get; set; }
        public int? Dept_Id { get; set; }
        public int? St_super { get; set; }
    }
}
