// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DataBase_First.Models;

public partial class StudentsAge
{
    public string? StFname { get; set; }

    public int? StAge { get; set; }
}