// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DataBase_First.Models;

public partial class StudentGrade
{
    public string? FullName { get; set; }

    public string? CrsName { get; set; }
}