// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DataBase_First.Models;

public partial class StudentsInDepartment
{
    public int StudentIdentifier { get; set; }

    public string? StudentName { get; set; }

    public int? StudentDeptId { get; set; }

    public int DeptIdentifier { get; set; }

    public string? DeptName { get; set; }
}