// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DataBase_First.Models;

public partial class StudentWithAddressAlex
{
    public int Id { get; set; }

    public string? Fname { get; set; }

    public string? Address { get; set; }
}