// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DataBase_First.Models;

public partial class StudentAudit
{
    public string? ServerUserName { get; set; }

    public DateOnly? Date { get; set; }

    public string? Note { get; set; }
}