// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace DataBase_First.Models;

public partial class VstudentsInDepartment
{
    public int StId { get; set; }

    public string? StFname { get; set; }

    public int DeptId { get; set; }

    public string? DeptName { get; set; }
}